version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/ssl
    networks:
      - wordpress-network
  mysql-wordpress:
    image: mysql
    networks:
      - wordpress-network
    volumes:
      - ./mysql-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: giraffe0928
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: wordpress-user
      MYSQL_PASSWORD: wordpress0928
  wordpress:
    depends_on:
      - mysql-wordpress
    image: wordpress
    networks:
      - wordpress-network
    volumes:
      - ./wordpress-volume:/var/www/html
    #ports:
    #  - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql-wordpress
      WORDPRESS_DB_NAME: wordpress-db
      WORDPRESS_DB_USER: wordpress-user
      WORDPRESS_DB_PASSWORD: wordpress0928
networks:
  wordpress-network:
volumes:
  mysql-volume:
  wordpress-volume: