apiVersion: v1
kind: Service
metadata:
  name: k8s-test-service
spec:
  selector:
    app: sanic-k8s
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8080
    #nodePort: 30390
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-qing-service
spec:
  selector:
    app: sanic-k8s-qing
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8080